### ISSUE TITLE
Các nhánh bị chèn khi pull

### ISSUE THREAD

**Issue by tuthihue** [UIT-21522109/SNAKE#24]

**Comment by lapetitdiem** [comment]
Xem nhánh trước được làm tới code thứ mấy thì nhánh sau làm tiếp tục xuống code tiếp theo
Nếu code rồi thì copy hoặc xoá phần code đó đưa xuống phía dưới phần trống

**Comment by tuthihue** [comment]
[https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github]
tham khảo hướng dẫn sửa oke r nha

**Comment by lapetitdiem** [comment]
okela
