### ISSUE TITLE
Hàm pause

### ISSUE THREAD

**Issue by tuthihue** [UIT-21522109/SNAKE#43]
khi nhấn n
ko thoát ra khỏi màng hình chơi

**Comment by UIT-21522190** [comment]
theo ý kiến của tui sửa: 
void pause()
{
    char c;
    cout<<""<<endl<<endl;
    cout<<"Game over. Do you want to play again? [y/n]  ";
    cin>>c;
    if(c=='y') return;
    else if(c=='n')
    {
        system("cls");
            main();
    }
}
